version: "3.9"

services:
  web:
    build: .
    container_name: flask_web_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
