version: "3.9"

services:
  flask:
    build: .
    container_name: flask_app
    restart: always
    expose:
      - "5000"
    volumes:
      - .:/app

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - flask
